name:                melllk
version:             0.1.0.0
github:              "githubuser/melllk"
license:             BSD3
author:              "linguini"
maintainer:          "example@example.com"
copyright:           "2019 linguini"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/melllk#readme>

dependencies:
- base >= 4.7 && < 5
- safe
- containers
- text
- mtl
- megaparsec
- pretty-simple

library:
  source-dirs: src

executables:
  melllk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melllk

tests:
  melllk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melllk
